---
galaxy_info:
  author: dukex <emersonalmeidax@gmail.com>
  description: FiveM runtime artifact download and version management
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - fivem
    - gameserver
    - runtime
    - artifacts

dependencies: []
