---
galaxy_info:
  author: dukex <emersonalmeidax@gmail.com>
  description: Nginx reverse proxy for FiveM server with TCP/UDP stream support
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - fivem
    - gameserver
    - nginx
    - proxy
    - cloudflare

dependencies: []
