---
# FiveM Server MariaDB - Main Tasks

- name: Include installation tasks
  include_tasks: install.yml
  tags:
    - database
    - database_install

- name: Include security tasks
  include_tasks: security.yml
  tags:
    - database
    - database_security

- name: Include database creation tasks
  include_tasks: database.yml
  tags:
    - database
    - database_fivem

- name: Include configuration tasks
  include_tasks: configuration.yml
  tags:
    - database
    - database_configuration
